//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroCMS.Plugin.NefKandilli.NEFWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Webform", Namespace="http://schemas.datacontract.org/2004/07/NEF.WebServices.WebForm")]
    [System.SerializableAttribute()]
    public partial class Webform : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelOfAwarenessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.ContactPreferences> ContactPreferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.InvestmentRange> CustomerInvestmentRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerMobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.FlatType> FlatTypeChooseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InterestOfProjectCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.Location> LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NefInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PersonalDataSecurityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.ProcessType> ProcessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubParticipationSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UTM_CampaignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UTM_MediumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> utmAdWordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelOfAwareness {
            get {
                return this.ChannelOfAwarenessField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelOfAwarenessField, value) != true)) {
                    this.ChannelOfAwarenessField = value;
                    this.RaisePropertyChanged("ChannelOfAwareness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.ContactPreferences> ContactPreferences {
            get {
                return this.ContactPreferencesField;
            }
            set {
                if ((this.ContactPreferencesField.Equals(value) != true)) {
                    this.ContactPreferencesField = value;
                    this.RaisePropertyChanged("ContactPreferences");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.InvestmentRange> CustomerInvestmentRange {
            get {
                return this.CustomerInvestmentRangeField;
            }
            set {
                if ((this.CustomerInvestmentRangeField.Equals(value) != true)) {
                    this.CustomerInvestmentRangeField = value;
                    this.RaisePropertyChanged("CustomerInvestmentRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerMobilePhone {
            get {
                return this.CustomerMobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerMobilePhoneField, value) != true)) {
                    this.CustomerMobilePhoneField = value;
                    this.RaisePropertyChanged("CustomerMobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.FlatType> FlatTypeChoose {
            get {
                return this.FlatTypeChooseField;
            }
            set {
                if ((this.FlatTypeChooseField.Equals(value) != true)) {
                    this.FlatTypeChooseField = value;
                    this.RaisePropertyChanged("FlatTypeChoose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterestOfProjectCode {
            get {
                return this.InterestOfProjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.InterestOfProjectCodeField, value) != true)) {
                    this.InterestOfProjectCodeField = value;
                    this.RaisePropertyChanged("InterestOfProjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.Location> Location {
            get {
                return this.LocationField;
            }
            set {
                if ((this.LocationField.Equals(value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NefInformation {
            get {
                return this.NefInformationField;
            }
            set {
                if ((this.NefInformationField.Equals(value) != true)) {
                    this.NefInformationField = value;
                    this.RaisePropertyChanged("NefInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PersonalDataSecurity {
            get {
                return this.PersonalDataSecurityField;
            }
            set {
                if ((this.PersonalDataSecurityField.Equals(value) != true)) {
                    this.PersonalDataSecurityField = value;
                    this.RaisePropertyChanged("PersonalDataSecurity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EuroCMS.Plugin.NefKandilli.NEFWebService.ProcessType> ProcessType {
            get {
                return this.ProcessTypeField;
            }
            set {
                if ((this.ProcessTypeField.Equals(value) != true)) {
                    this.ProcessTypeField = value;
                    this.RaisePropertyChanged("ProcessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubParticipationSource {
            get {
                return this.SubParticipationSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SubParticipationSourceField, value) != true)) {
                    this.SubParticipationSourceField = value;
                    this.RaisePropertyChanged("SubParticipationSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UTM_Campaign {
            get {
                return this.UTM_CampaignField;
            }
            set {
                if ((object.ReferenceEquals(this.UTM_CampaignField, value) != true)) {
                    this.UTM_CampaignField = value;
                    this.RaisePropertyChanged("UTM_Campaign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UTM_Medium {
            get {
                return this.UTM_MediumField;
            }
            set {
                if ((object.ReferenceEquals(this.UTM_MediumField, value) != true)) {
                    this.UTM_MediumField = value;
                    this.RaisePropertyChanged("UTM_Medium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> utmAdWords {
            get {
                return this.utmAdWordsField;
            }
            set {
                if ((this.utmAdWordsField.Equals(value) != true)) {
                    this.utmAdWordsField = value;
                    this.RaisePropertyChanged("utmAdWords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPreferences", Namespace="http://schemas.datacontract.org/2004/07/NEF.WebServices.WebForm")]
    public enum ContactPreferences : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Phone = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMail = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvestmentRange", Namespace="http://schemas.datacontract.org/2004/07/NEF.WebServices.WebForm")]
    public enum InvestmentRange : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionOne = 100000000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionTwo = 100000001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionThree = 100000002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionFour = 100000003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionFive = 100000004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionSix = 100000005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionSeven = 100000006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionEight = 100000007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionNine = 100000008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionTen = 100000009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionEleven = 1000000010,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatType", Namespace="http://schemas.datacontract.org/2004/07/NEF.WebServices.WebForm")]
    public enum FlatType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionOne = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionTwo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionThree = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionFour = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionFive = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionSix = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionSeven = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionEight = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionNine = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionTen = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionEleven = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        optionTwelve = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/NEF.WebServices.WebForm")]
    public enum Location : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Merter = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kağıthane = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessType", Namespace="http://schemas.datacontract.org/2004/07/NEF.WebServices.WebForm")]
    public enum ProcessType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForSale = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForRent = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsCrmResult", Namespace="http://schemas.datacontract.org/2004/07/NEF.WebServices.WebForm")]
    [System.SerializableAttribute()]
    public partial class MsCrmResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NEFWebService.IWebForm")]
    public interface IWebForm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebForm/CreateWebForm", ReplyAction="http://tempuri.org/IWebForm/CreateWebFormResponse")]
        EuroCMS.Plugin.NefKandilli.NEFWebService.MsCrmResult CreateWebForm(EuroCMS.Plugin.NefKandilli.NEFWebService.Webform form);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebForm/CreateWebForm", ReplyAction="http://tempuri.org/IWebForm/CreateWebFormResponse")]
        System.Threading.Tasks.Task<EuroCMS.Plugin.NefKandilli.NEFWebService.MsCrmResult> CreateWebFormAsync(EuroCMS.Plugin.NefKandilli.NEFWebService.Webform form);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebFormChannel : EuroCMS.Plugin.NefKandilli.NEFWebService.IWebForm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebFormClient : System.ServiceModel.ClientBase<EuroCMS.Plugin.NefKandilli.NEFWebService.IWebForm>, EuroCMS.Plugin.NefKandilli.NEFWebService.IWebForm {
        
        public WebFormClient() {
        }
        
        public WebFormClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebFormClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebFormClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebFormClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EuroCMS.Plugin.NefKandilli.NEFWebService.MsCrmResult CreateWebForm(EuroCMS.Plugin.NefKandilli.NEFWebService.Webform form) {
            return base.Channel.CreateWebForm(form);
        }
        
        public System.Threading.Tasks.Task<EuroCMS.Plugin.NefKandilli.NEFWebService.MsCrmResult> CreateWebFormAsync(EuroCMS.Plugin.NefKandilli.NEFWebService.Webform form) {
            return base.Channel.CreateWebFormAsync(form);
        }
    }
}
