//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroCMS.Plugin.DExpert.RandevuService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCities", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class ResponseCities : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.cityCodeField, value) != true)) {
                    this.cityCodeField = value;
                    this.RaisePropertyChanged("cityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cityNameField, value) != true)) {
                    this.cityNameField = value;
                    this.RaisePropertyChanged("cityName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestSendSms", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class RequestSendSms : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerNameSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerNameSurname {
            get {
                return this.customerNameSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.customerNameSurnameField, value) != true)) {
                    this.customerNameSurnameField = value;
                    this.RaisePropertyChanged("customerNameSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respond2", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseCities>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.ResponseCities))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.RequestSendSms))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.RequestControlSms))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseTowns>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.ResponseTowns))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseProducts>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.ResponseProducts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseProductDetails>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.ResponseProductDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseContactChannels>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.ResponseContactChannels))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.RequestHoldBranch))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.RequestCreateAppointment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.RequestCancelAppointment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.RequestContactForm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.ResponseGetAppointment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.RequestUpdateAppointment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseExpertiseAim>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.ResponseExpertiseAim))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EuroCMS.Plugin.DExpert.RandevuService.RequestCreateSurvey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
    public partial class Respond2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestControlSms", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class RequestControlSms : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oneTimePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oneTimePassword {
            get {
                return this.oneTimePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.oneTimePasswordField, value) != true)) {
                    this.oneTimePasswordField = value;
                    this.RaisePropertyChanged("oneTimePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseTowns", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class ResponseTowns : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coordinateURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string townCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string townNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.branchCodeField, value) != true)) {
                    this.branchCodeField = value;
                    this.RaisePropertyChanged("branchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branchName {
            get {
                return this.branchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.branchNameField, value) != true)) {
                    this.branchNameField = value;
                    this.RaisePropertyChanged("branchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string coordinateURL {
            get {
                return this.coordinateURLField;
            }
            set {
                if ((object.ReferenceEquals(this.coordinateURLField, value) != true)) {
                    this.coordinateURLField = value;
                    this.RaisePropertyChanged("coordinateURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string townCode {
            get {
                return this.townCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.townCodeField, value) != true)) {
                    this.townCodeField = value;
                    this.RaisePropertyChanged("townCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string townName {
            get {
                return this.townNameField;
            }
            set {
                if ((object.ReferenceEquals(this.townNameField, value) != true)) {
                    this.townNameField = value;
                    this.RaisePropertyChanged("townName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseProducts", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class ResponseProducts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detailsUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal discountPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double discountRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal productPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detailsUrl {
            get {
                return this.detailsUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.detailsUrlField, value) != true)) {
                    this.detailsUrlField = value;
                    this.RaisePropertyChanged("detailsUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal discountPrice {
            get {
                return this.discountPriceField;
            }
            set {
                if ((this.discountPriceField.Equals(value) != true)) {
                    this.discountPriceField = value;
                    this.RaisePropertyChanged("discountPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double discountRate {
            get {
                return this.discountRateField;
            }
            set {
                if ((this.discountRateField.Equals(value) != true)) {
                    this.discountRateField = value;
                    this.RaisePropertyChanged("discountRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.productCodeField, value) != true)) {
                    this.productCodeField = value;
                    this.RaisePropertyChanged("productCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                if ((object.ReferenceEquals(this.productNameField, value) != true)) {
                    this.productNameField = value;
                    this.RaisePropertyChanged("productName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal productPrice {
            get {
                return this.productPriceField;
            }
            set {
                if ((this.productPriceField.Equals(value) != true)) {
                    this.productPriceField = value;
                    this.RaisePropertyChanged("productPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productTime {
            get {
                return this.productTimeField;
            }
            set {
                if ((this.productTimeField.Equals(value) != true)) {
                    this.productTimeField = value;
                    this.RaisePropertyChanged("productTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseProductDetails", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class ResponseProductDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodcutDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> propertyDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodcutDetail {
            get {
                return this.prodcutDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.prodcutDetailField, value) != true)) {
                    this.prodcutDetailField = value;
                    this.RaisePropertyChanged("prodcutDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> propertyDetails {
            get {
                return this.propertyDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.propertyDetailsField, value) != true)) {
                    this.propertyDetailsField = value;
                    this.RaisePropertyChanged("propertyDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContactChannels", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class ResponseContactChannels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contactName {
            get {
                return this.contactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.contactNameField, value) != true)) {
                    this.contactNameField = value;
                    this.RaisePropertyChanged("contactName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestHoldBranch", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class RequestHoldBranch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime holdTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string holdTimeRangeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.branchCodeField, value) != true)) {
                    this.branchCodeField = value;
                    this.RaisePropertyChanged("branchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branchName {
            get {
                return this.branchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.branchNameField, value) != true)) {
                    this.branchNameField = value;
                    this.RaisePropertyChanged("branchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime holdTime {
            get {
                return this.holdTimeField;
            }
            set {
                if ((this.holdTimeField.Equals(value) != true)) {
                    this.holdTimeField = value;
                    this.RaisePropertyChanged("holdTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string holdTimeRange {
            get {
                return this.holdTimeRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.holdTimeRangeField, value) != true)) {
                    this.holdTimeRangeField = value;
                    this.RaisePropertyChanged("holdTimeRange");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestCreateAppointment", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class RequestCreateAppointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime appointmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expertiseAimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expertisePackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string finishHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string finishMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isEmailSmsSubmitAcceptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isEtrateAcceptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isKVKKAcceptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isSendMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isSendSmsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime varAppointmentDateFlowTrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime appointmentDate {
            get {
                return this.appointmentDateField;
            }
            set {
                if ((this.appointmentDateField.Equals(value) != true)) {
                    this.appointmentDateField = value;
                    this.RaisePropertyChanged("appointmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.branchCodeField, value) != true)) {
                    this.branchCodeField = value;
                    this.RaisePropertyChanged("branchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expertiseAim {
            get {
                return this.expertiseAimField;
            }
            set {
                if ((object.ReferenceEquals(this.expertiseAimField, value) != true)) {
                    this.expertiseAimField = value;
                    this.RaisePropertyChanged("expertiseAim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expertisePackage {
            get {
                return this.expertisePackageField;
            }
            set {
                if ((object.ReferenceEquals(this.expertisePackageField, value) != true)) {
                    this.expertisePackageField = value;
                    this.RaisePropertyChanged("expertisePackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string finishHour {
            get {
                return this.finishHourField;
            }
            set {
                if ((object.ReferenceEquals(this.finishHourField, value) != true)) {
                    this.finishHourField = value;
                    this.RaisePropertyChanged("finishHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string finishMinute {
            get {
                return this.finishMinuteField;
            }
            set {
                if ((object.ReferenceEquals(this.finishMinuteField, value) != true)) {
                    this.finishMinuteField = value;
                    this.RaisePropertyChanged("finishMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isEmailSmsSubmitAccept {
            get {
                return this.isEmailSmsSubmitAcceptField;
            }
            set {
                if ((this.isEmailSmsSubmitAcceptField.Equals(value) != true)) {
                    this.isEmailSmsSubmitAcceptField = value;
                    this.RaisePropertyChanged("isEmailSmsSubmitAccept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isEtrateAccept {
            get {
                return this.isEtrateAcceptField;
            }
            set {
                if ((this.isEtrateAcceptField.Equals(value) != true)) {
                    this.isEtrateAcceptField = value;
                    this.RaisePropertyChanged("isEtrateAccept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isKVKKAccept {
            get {
                return this.isKVKKAcceptField;
            }
            set {
                if ((this.isKVKKAcceptField.Equals(value) != true)) {
                    this.isKVKKAcceptField = value;
                    this.RaisePropertyChanged("isKVKKAccept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isSendMail {
            get {
                return this.isSendMailField;
            }
            set {
                if ((this.isSendMailField.Equals(value) != true)) {
                    this.isSendMailField = value;
                    this.RaisePropertyChanged("isSendMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isSendSms {
            get {
                return this.isSendSmsField;
            }
            set {
                if ((this.isSendSmsField.Equals(value) != true)) {
                    this.isSendSmsField = value;
                    this.RaisePropertyChanged("isSendSms");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startHour {
            get {
                return this.startHourField;
            }
            set {
                if ((object.ReferenceEquals(this.startHourField, value) != true)) {
                    this.startHourField = value;
                    this.RaisePropertyChanged("startHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startMinute {
            get {
                return this.startMinuteField;
            }
            set {
                if ((object.ReferenceEquals(this.startMinuteField, value) != true)) {
                    this.startMinuteField = value;
                    this.RaisePropertyChanged("startMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime varAppointmentDateFlowTr {
            get {
                return this.varAppointmentDateFlowTrField;
            }
            set {
                if ((this.varAppointmentDateFlowTrField.Equals(value) != true)) {
                    this.varAppointmentDateFlowTrField = value;
                    this.RaisePropertyChanged("varAppointmentDateFlowTr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestCancelAppointment", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class RequestCancelAppointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formGlobalIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formGlobalId {
            get {
                return this.formGlobalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.formGlobalIdField, value) != true)) {
                    this.formGlobalIdField = value;
                    this.RaisePropertyChanged("formGlobalId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestContactForm", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class RequestContactForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isEmailSmsSubmitAcceptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isKVKKAcceptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isEmailSmsSubmitAccept {
            get {
                return this.isEmailSmsSubmitAcceptField;
            }
            set {
                if ((this.isEmailSmsSubmitAcceptField.Equals(value) != true)) {
                    this.isEmailSmsSubmitAcceptField = value;
                    this.RaisePropertyChanged("isEmailSmsSubmitAccept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isKVKKAccept {
            get {
                return this.isKVKKAcceptField;
            }
            set {
                if ((this.isKVKKAcceptField.Equals(value) != true)) {
                    this.isKVKKAcceptField = value;
                    this.RaisePropertyChanged("isKVKKAccept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseGetAppointment", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class ResponseGetAppointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aimIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aimNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime appointmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appointmentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string finishHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string finishMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hearInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hearInfoCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string packageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string packageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txtCustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txtSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txtTownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txtcityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aimID {
            get {
                return this.aimIDField;
            }
            set {
                if ((object.ReferenceEquals(this.aimIDField, value) != true)) {
                    this.aimIDField = value;
                    this.RaisePropertyChanged("aimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aimName {
            get {
                return this.aimNameField;
            }
            set {
                if ((object.ReferenceEquals(this.aimNameField, value) != true)) {
                    this.aimNameField = value;
                    this.RaisePropertyChanged("aimName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime appointmentDate {
            get {
                return this.appointmentDateField;
            }
            set {
                if ((this.appointmentDateField.Equals(value) != true)) {
                    this.appointmentDateField = value;
                    this.RaisePropertyChanged("appointmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string appointmentStatus {
            get {
                return this.appointmentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.appointmentStatusField, value) != true)) {
                    this.appointmentStatusField = value;
                    this.RaisePropertyChanged("appointmentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.branchCodeField, value) != true)) {
                    this.branchCodeField = value;
                    this.RaisePropertyChanged("branchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branchName {
            get {
                return this.branchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.branchNameField, value) != true)) {
                    this.branchNameField = value;
                    this.RaisePropertyChanged("branchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string finishHour {
            get {
                return this.finishHourField;
            }
            set {
                if ((object.ReferenceEquals(this.finishHourField, value) != true)) {
                    this.finishHourField = value;
                    this.RaisePropertyChanged("finishHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string finishMinute {
            get {
                return this.finishMinuteField;
            }
            set {
                if ((object.ReferenceEquals(this.finishMinuteField, value) != true)) {
                    this.finishMinuteField = value;
                    this.RaisePropertyChanged("finishMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hearInfo {
            get {
                return this.hearInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.hearInfoField, value) != true)) {
                    this.hearInfoField = value;
                    this.RaisePropertyChanged("hearInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hearInfoComment {
            get {
                return this.hearInfoCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.hearInfoCommentField, value) != true)) {
                    this.hearInfoCommentField = value;
                    this.RaisePropertyChanged("hearInfoComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string packageID {
            get {
                return this.packageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.packageIDField, value) != true)) {
                    this.packageIDField = value;
                    this.RaisePropertyChanged("packageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string packageName {
            get {
                return this.packageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.packageNameField, value) != true)) {
                    this.packageNameField = value;
                    this.RaisePropertyChanged("packageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodTime {
            get {
                return this.prodTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.prodTimeField, value) != true)) {
                    this.prodTimeField = value;
                    this.RaisePropertyChanged("prodTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startHour {
            get {
                return this.startHourField;
            }
            set {
                if ((object.ReferenceEquals(this.startHourField, value) != true)) {
                    this.startHourField = value;
                    this.RaisePropertyChanged("startHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startMinute {
            get {
                return this.startMinuteField;
            }
            set {
                if ((object.ReferenceEquals(this.startMinuteField, value) != true)) {
                    this.startMinuteField = value;
                    this.RaisePropertyChanged("startMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string txtCustomerName {
            get {
                return this.txtCustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.txtCustomerNameField, value) != true)) {
                    this.txtCustomerNameField = value;
                    this.RaisePropertyChanged("txtCustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string txtSurname {
            get {
                return this.txtSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.txtSurnameField, value) != true)) {
                    this.txtSurnameField = value;
                    this.RaisePropertyChanged("txtSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string txtTown {
            get {
                return this.txtTownField;
            }
            set {
                if ((object.ReferenceEquals(this.txtTownField, value) != true)) {
                    this.txtTownField = value;
                    this.RaisePropertyChanged("txtTown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string txtcity {
            get {
                return this.txtcityField;
            }
            set {
                if ((object.ReferenceEquals(this.txtcityField, value) != true)) {
                    this.txtcityField = value;
                    this.RaisePropertyChanged("txtcity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestUpdateAppointment", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class RequestUpdateAppointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formGlobalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string newAimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime newAppointmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string newAppointmentHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string newBranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string newBranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string newProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string updateTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formGlobalId {
            get {
                return this.formGlobalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.formGlobalIdField, value) != true)) {
                    this.formGlobalIdField = value;
                    this.RaisePropertyChanged("formGlobalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string newAim {
            get {
                return this.newAimField;
            }
            set {
                if ((object.ReferenceEquals(this.newAimField, value) != true)) {
                    this.newAimField = value;
                    this.RaisePropertyChanged("newAim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime newAppointmentDate {
            get {
                return this.newAppointmentDateField;
            }
            set {
                if ((this.newAppointmentDateField.Equals(value) != true)) {
                    this.newAppointmentDateField = value;
                    this.RaisePropertyChanged("newAppointmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string newAppointmentHour {
            get {
                return this.newAppointmentHourField;
            }
            set {
                if ((object.ReferenceEquals(this.newAppointmentHourField, value) != true)) {
                    this.newAppointmentHourField = value;
                    this.RaisePropertyChanged("newAppointmentHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string newBranchCode {
            get {
                return this.newBranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.newBranchCodeField, value) != true)) {
                    this.newBranchCodeField = value;
                    this.RaisePropertyChanged("newBranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string newBranchName {
            get {
                return this.newBranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.newBranchNameField, value) != true)) {
                    this.newBranchNameField = value;
                    this.RaisePropertyChanged("newBranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string newProductName {
            get {
                return this.newProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.newProductNameField, value) != true)) {
                    this.newProductNameField = value;
                    this.RaisePropertyChanged("newProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string updateType {
            get {
                return this.updateTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.updateTypeField, value) != true)) {
                    this.updateTypeField = value;
                    this.RaisePropertyChanged("updateType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseExpertiseAim", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class ResponseExpertiseAim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aimIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aimNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aimID {
            get {
                return this.aimIDField;
            }
            set {
                if ((object.ReferenceEquals(this.aimIDField, value) != true)) {
                    this.aimIDField = value;
                    this.RaisePropertyChanged("aimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aimName {
            get {
                return this.aimNameField;
            }
            set {
                if ((object.ReferenceEquals(this.aimNameField, value) != true)) {
                    this.aimNameField = value;
                    this.RaisePropertyChanged("aimName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestCreateSurvey", Namespace="http://schemas.datacontract.org/2004/07/D_Expert_AppointmentWService_Lib")]
    [System.SerializableAttribute()]
    public partial class RequestCreateSurvey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appointmentFormIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactChannelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string otherContactField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string appointmentFormId {
            get {
                return this.appointmentFormIdField;
            }
            set {
                if ((object.ReferenceEquals(this.appointmentFormIdField, value) != true)) {
                    this.appointmentFormIdField = value;
                    this.RaisePropertyChanged("appointmentFormId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contactChannelId {
            get {
                return this.contactChannelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.contactChannelIdField, value) != true)) {
                    this.contactChannelIdField = value;
                    this.RaisePropertyChanged("contactChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string otherContact {
            get {
                return this.otherContactField;
            }
            set {
                if ((object.ReferenceEquals(this.otherContactField, value) != true)) {
                    this.otherContactField = value;
                    this.RaisePropertyChanged("otherContact");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RandevuService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Test", ReplyAction="http://tempuri.org/IService/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCities", ReplyAction="http://tempuri.org/IService/GetCitiesResponse")]
        System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseCities> GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendSms", ReplyAction="http://tempuri.org/IService/SendSmsResponse")]
        EuroCMS.Plugin.DExpert.RandevuService.Respond2 SendSms(EuroCMS.Plugin.DExpert.RandevuService.RequestSendSms request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ControlSms", ReplyAction="http://tempuri.org/IService/ControlSmsResponse")]
        bool ControlSms(EuroCMS.Plugin.DExpert.RandevuService.RequestControlSms request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTowns", ReplyAction="http://tempuri.org/IService/GetTownsResponse")]
        System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseTowns> GetTowns(string cityCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProducts", ReplyAction="http://tempuri.org/IService/GetProductsResponse")]
        System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseProducts> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductDetail", ReplyAction="http://tempuri.org/IService/GetProductDetailResponse")]
        System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseProductDetails> GetProductDetail(string productCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetContactChannels", ReplyAction="http://tempuri.org/IService/GetContactChannelsResponse")]
        System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseContactChannels> GetContactChannels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/HoldSession", ReplyAction="http://tempuri.org/IService/HoldSessionResponse")]
        bool HoldSession(EuroCMS.Plugin.DExpert.RandevuService.RequestHoldBranch req_holdBranch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateAppointment", ReplyAction="http://tempuri.org/IService/CreateAppointmentResponse")]
        EuroCMS.Plugin.DExpert.RandevuService.Respond2 CreateAppointment(EuroCMS.Plugin.DExpert.RandevuService.RequestCreateAppointment req_CreateAppointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelAppointment", ReplyAction="http://tempuri.org/IService/CancelAppointmentResponse")]
        EuroCMS.Plugin.DExpert.RandevuService.Respond2 CancelAppointment(EuroCMS.Plugin.DExpert.RandevuService.RequestCancelAppointment req_CancelAppointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateContactForm", ReplyAction="http://tempuri.org/IService/CreateContactFormResponse")]
        EuroCMS.Plugin.DExpert.RandevuService.Respond2 CreateContactForm(EuroCMS.Plugin.DExpert.RandevuService.RequestContactForm req_ContactForm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSuitableDates", ReplyAction="http://tempuri.org/IService/getSuitableDatesResponse")]
        System.Collections.Generic.List<string> getSuitableDates(string branchCode, int productTime, int minutePeriod, int dayLength);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSuitableHours", ReplyAction="http://tempuri.org/IService/getSuitableHoursResponse")]
        System.Collections.Generic.List<string> getSuitableHours(System.DateTime date, string branchCode, int productTime, int minutePeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAppointment", ReplyAction="http://tempuri.org/IService/GetAppointmentResponse")]
        EuroCMS.Plugin.DExpert.RandevuService.ResponseGetAppointment GetAppointment(string formGlobalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAppointment", ReplyAction="http://tempuri.org/IService/UpdateAppointmentResponse")]
        EuroCMS.Plugin.DExpert.RandevuService.Respond2 UpdateAppointment(EuroCMS.Plugin.DExpert.RandevuService.RequestUpdateAppointment req_updateAppointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetExpertiseAim", ReplyAction="http://tempuri.org/IService/GetExpertiseAimResponse")]
        System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseExpertiseAim> GetExpertiseAim();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateSurvey", ReplyAction="http://tempuri.org/IService/CreateSurveyResponse")]
        EuroCMS.Plugin.DExpert.RandevuService.Respond2 CreateSurvey(EuroCMS.Plugin.DExpert.RandevuService.RequestCreateSurvey req_CreateSurvey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOTPStatus", ReplyAction="http://tempuri.org/IService/GetOTPStatusResponse")]
        bool GetOTPStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductsByAim", ReplyAction="http://tempuri.org/IService/GetProductsByAimResponse")]
        System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseProducts> GetProductsByAim(string aimID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : EuroCMS.Plugin.DExpert.RandevuService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<EuroCMS.Plugin.DExpert.RandevuService.IService>, EuroCMS.Plugin.DExpert.RandevuService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseCities> GetCities() {
            return base.Channel.GetCities();
        }
        
        public EuroCMS.Plugin.DExpert.RandevuService.Respond2 SendSms(EuroCMS.Plugin.DExpert.RandevuService.RequestSendSms request) {
            return base.Channel.SendSms(request);
        }
        
        public bool ControlSms(EuroCMS.Plugin.DExpert.RandevuService.RequestControlSms request) {
            return base.Channel.ControlSms(request);
        }
        
        public System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseTowns> GetTowns(string cityCode) {
            return base.Channel.GetTowns(cityCode);
        }
        
        public System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseProducts> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseProductDetails> GetProductDetail(string productCode) {
            return base.Channel.GetProductDetail(productCode);
        }
        
        public System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseContactChannels> GetContactChannels() {
            return base.Channel.GetContactChannels();
        }
        
        public bool HoldSession(EuroCMS.Plugin.DExpert.RandevuService.RequestHoldBranch req_holdBranch) {
            return base.Channel.HoldSession(req_holdBranch);
        }
        
        public EuroCMS.Plugin.DExpert.RandevuService.Respond2 CreateAppointment(EuroCMS.Plugin.DExpert.RandevuService.RequestCreateAppointment req_CreateAppointment) {
            return base.Channel.CreateAppointment(req_CreateAppointment);
        }
        
        public EuroCMS.Plugin.DExpert.RandevuService.Respond2 CancelAppointment(EuroCMS.Plugin.DExpert.RandevuService.RequestCancelAppointment req_CancelAppointment) {
            return base.Channel.CancelAppointment(req_CancelAppointment);
        }
        
        public EuroCMS.Plugin.DExpert.RandevuService.Respond2 CreateContactForm(EuroCMS.Plugin.DExpert.RandevuService.RequestContactForm req_ContactForm) {
            return base.Channel.CreateContactForm(req_ContactForm);
        }
        
        public System.Collections.Generic.List<string> getSuitableDates(string branchCode, int productTime, int minutePeriod, int dayLength) {
            return base.Channel.getSuitableDates(branchCode, productTime, minutePeriod, dayLength);
        }
        
        public System.Collections.Generic.List<string> getSuitableHours(System.DateTime date, string branchCode, int productTime, int minutePeriod) {
            return base.Channel.getSuitableHours(date, branchCode, productTime, minutePeriod);
        }
        
        public EuroCMS.Plugin.DExpert.RandevuService.ResponseGetAppointment GetAppointment(string formGlobalId) {
            return base.Channel.GetAppointment(formGlobalId);
        }
        
        public EuroCMS.Plugin.DExpert.RandevuService.Respond2 UpdateAppointment(EuroCMS.Plugin.DExpert.RandevuService.RequestUpdateAppointment req_updateAppointment) {
            return base.Channel.UpdateAppointment(req_updateAppointment);
        }
        
        public System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseExpertiseAim> GetExpertiseAim() {
            return base.Channel.GetExpertiseAim();
        }
        
        public EuroCMS.Plugin.DExpert.RandevuService.Respond2 CreateSurvey(EuroCMS.Plugin.DExpert.RandevuService.RequestCreateSurvey req_CreateSurvey) {
            return base.Channel.CreateSurvey(req_CreateSurvey);
        }
        
        public bool GetOTPStatus() {
            return base.Channel.GetOTPStatus();
        }
        
        public System.Collections.Generic.List<EuroCMS.Plugin.DExpert.RandevuService.ResponseProducts> GetProductsByAim(string aimID) {
            return base.Channel.GetProductsByAim(aimID);
        }
    }
}
